title: Sofian EL ATIFI
url: "https://sofian-borel.github.io/SofianEAwebsite/"
baseurl: ""

markdown: kramdown

kramdown:
  math_engine: katex

sass:
    style: compressed
    sass_dir: _sass

favicon: true

nav:
  - name: "About"
    link: "/en/about"
    lang: "en"
  - name: "Research"
    link: "/en/research"
    lang: "en"
  - name: "Resources"
    link: "/en/resources"
    lang: "en"
  - name: "Contact"
    link: "/en/contact"
    lang: "en"
