title: Sofian EL ATIFI
url: "https://sofian-borel.github.io"
baseurl: "/SofianEAwebsite" # If hosted in a subdirectory

markdown: kramdown

kramdown:
  math_engine: katex

sass:
  style: compressed
  sass_dir: _sass

# Navigation: Ensure these files exist at the specified paths
nav:
  - name: "About"
    link: "/SofianEAwebsite/en/about/"
    lang: "en"
  - name: "Research"
    link: "/SofianEAwebsite/en/research/"
    lang: "en"
  - name: "Resources"
    link: "/SofianEAwebsite/en/resources/"
    lang: "en"
  - name: "Contact"
    link: "/SofianEAwebsite/en/contact/"
    lang: "en"
