title: Benjamin GILBERT
url: "https://bglbrt.github.io"
baseurl: ""

markdown: kramdown

kramdown:
  math_engine: katex

sass:
    style: compressed
    sass_dir: _sass

favicon: true

nav:
  - name: "About"
    link: "/en/about.md"
    lang: "en"
  - name: "Research"
    link: "/en/research.md"
    lang: "en"
  - name: "Resources"
    link: "/en/resources.md"
    lang: "en"
  - name: "Resume"
    link: "/en/resume.pdf"
    lang: "en"
  - name: "Contact"
    link: "/en/contact.md"
    lang: "en"
