title: Sofian EL ATIFI
url: "https://sofian-borel.github.io/SofianEAwebsite/"
baseurl: ""

markdown: kramdown

kramdown:
  math_engine: katex

sass:
    style: compressed
    sass_dir: _sass

favicon: true

nav:
  - name: "About"
    link: "/en/about.md"
    lang: "en"
  - name: "Research"
    link: "/en/research.md"
    lang: "en"
  - name: "Resources"
    link: "/en/resources.md"
    lang: "en"
  - name: "Contact"
    link: "/en/contact.md"
    lang: "en"
