title: Sofian EL ATIFI
url: "https://sofian-borel.github.io"
baseurl: "/SofianEAwebsite" # If hosted in a subdirectory

markdown: kramdown

kramdown:
  math_engine: katex

sass:
  style: compressed
  sass_dir: _sass

# Navigation: Ensure these files exist at the specified paths
nav:
  - name: "About"
    link: "/about/"
  - name: "Research"
    link: "/research/"
  - name: "Resources"
    link: "/resources/"
  - name: "Contact"
    link: "/contact/"
  - name: "CV"
    link: "/cv/"
